const actividadesLista=['Trabajo de Riesgo en Altura','Trabajo de Riesgo en Caliente','Trabajo en Espacio Confinado','Trabajo de Riesgo Eléctrico','Trabajo de Riesgo en Izaje','Trabajo de Riesgo en MAPTEL','Otros riesgos'];
const sintomasLista=['Dolor de cabeza','Mareos o inestabilidad','Visión borrosa','Náuseas o vómitos','Dolor en el pecho','Dificultad para respirar','Fatiga o somnolencia','Consumo de alcohol o drogas'];
let chartEmpresas, chartCondicion;
const get=(k)=>JSON.parse(localStorage.getItem(k)||'[]');
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

function seed(){if(!localStorage.getItem('trabajadores')){set('trabajadores',[{dni:'45910198',nombres:'Romero Lagos Jonathan',cargo:'Prevencionista',empresa:'Unacem',sede:'Planta Atocongo',rubro:'Cemento',correo:'jonathan.romero@unacem.pe',estado:'Activo'},{dni:'40875678',nombres:'Cersso Muro Lizette Cristina',cargo:'Médico Ocupacional',empresa:'Unacem',sede:'Planta Atocongo',rubro:'Cemento',correo:'',estado:'Activo'},{dni:'41235467',nombres:'Salas Diaz Luis',cargo:'Soldador',empresa:'HAUG',sede:'Planta Atocongo',rubro:'Cemento',correo:'',estado:'Activo'},{dni:'40564356',nombres:'Cuadros Solis Raul',cargo:'Oficial Mecánico',empresa:'CIME',sede:'Planta Atocongo',rubro:'Cemento',correo:'',estado:'Activo'}]);}}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');renderAll();}
function buildQuestions(){document.getElementById('actividades').innerHTML=actividadesLista.map((q,i)=>`<div class="question"><span>${q}</span><span><label><input type="radio" name="act${i}" value="SI"> SI</label><label><input type="radio" name="act${i}" value="NO" checked> NO</label></span></div>`).join('');document.getElementById('sintomas').innerHTML=sintomasLista.map((q,i)=>`<div class="question"><span>${q}</span><span><label><input type="radio" name="sin${i}" value="SI"> SI</label><label><input type="radio" name="sin${i}" value="NO" checked> NO</label></span></div>`).join('');}
function buscarTrabajador(){const dni=document.getElementById('dniBuscar').value.trim();const t=get('trabajadores').find(x=>x.dni===dni&&x.estado==='Activo');const box=document.getElementById('datosTrabajador'), form=document.getElementById('formReporte');if(!t){box.classList.remove('hidden');box.innerHTML='<b>No se encontró trabajador activo.</b><br>Coordine con su empresa para la carga de datos.';form.classList.add('hidden');return;}box.classList.remove('hidden');box.innerHTML=`<b>${t.nombres}</b><br>DNI: ${t.dni}<br>Cargo: ${t.cargo}<br>Empresa: ${t.empresa}<br>Sede: ${t.sede}`;form.classList.remove('hidden');form.dataset.dni=t.dni;}
document.getElementById('formReporte').addEventListener('submit',e=>{e.preventDefault();const dni=e.target.dataset.dni;const t=get('trabajadores').find(x=>x.dni===dni);const actividades=actividadesLista.map((q,i)=>({pregunta:q,respuesta:document.querySelector(`[name=act${i}]:checked`).value}));const sintomas=sintomasLista.map((q,i)=>({pregunta:q,respuesta:document.querySelector(`[name=sin${i}]:checked`).value}));const condicion=sintomas.some(x=>x.respuesta==='SI')?'Con síntomas':'Sin síntomas';const reportes=get('reportes');reportes.push({fecha:new Date().toISOString().slice(0,10),hora:new Date().toLocaleTimeString(),dni:t.dni,trabajador:t.nombres,cargo:t.cargo,empresa:t.empresa,sede:t.sede,actividades,sintomas,condicion,firma:document.getElementById('firma').value});set('reportes',reportes);alert('Reporte registrado correctamente: '+condicion);e.target.reset();document.getElementById('datosTrabajador').classList.add('hidden');e.target.classList.add('hidden');renderAll();});
function guardarTrabajador(){const t={dni:dni.value.trim(),nombres:nombres.value.trim(),cargo:cargo.value.trim(),empresa:empresaNombre.value.trim(),sede:sede.value.trim(),rubro:rubro.value.trim(),correo:correo.value.trim(),estado:estado.value};if(!t.dni||!t.nombres||!t.empresa)return alert('Complete DNI, nombres y empresa.');let arr=get('trabajadores').filter(x=>x.dni!==t.dni);arr.push(t);set('trabajadores',arr);document.querySelectorAll('#empresa input').forEach(i=>i.value='');renderAll();}
function importarCSV(ev){const file=ev.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean);const head=lines.shift().split(',').map(h=>h.trim().toLowerCase());let arr=get('trabajadores');lines.forEach(line=>{const vals=line.split(',');let o={estado:'Activo'};head.forEach((h,i)=>o[h]=vals[i]?.trim()||'');if(o.dni)arr=arr.filter(x=>x.dni!==o.dni).concat(o);});set('trabajadores',arr);renderAll();alert('CSV importado.');};r.readAsText(file);}
function renderTrabajadores(){const arr=get('trabajadores');tablaTrabajadores.innerHTML='<tr><th>DNI</th><th>Nombres</th><th>Cargo</th><th>Empresa</th><th>Sede</th><th>Estado</th></tr>'+arr.map(t=>`<tr><td>${t.dni}</td><td>${t.nombres}</td><td>${t.cargo}</td><td>${t.empresa}</td><td>${t.sede}</td><td>${t.estado}</td></tr>`).join('');empresaFiltro.innerHTML='<option value="">Todas las empresas</option>'+[...new Set(arr.map(x=>x.empresa).filter(Boolean))].map(e=>`<option>${e}</option>`).join('');}
function renderDashboard(){let reps=get('reportes'), trab=get('trabajadores').filter(x=>x.estado==='Activo');const f=fechaFiltro.value, emp=empresaFiltro.value;if(f)reps=reps.filter(r=>r.fecha===f);if(emp){reps=reps.filter(r=>r.empresa===emp);trab=trab.filter(t=>t.empresa===emp);}kpiTrabajadores.textContent=trab.length;kpiReportes.textContent=reps.length;kpiCumplimiento.textContent=trab.length?Math.round((new Set(reps.map(r=>r.dni)).size/trab.length)*100)+'%':'0%';kpiAlertas.textContent=reps.filter(r=>r.condicion==='Con síntomas').length;tablaReportes.innerHTML='<tr><th>Fecha</th><th>Trabajador</th><th>Empresa</th><th>Cargo</th><th>Condición</th></tr>'+reps.slice().reverse().map(r=>`<tr><td>${r.fecha}</td><td>${r.trabajador}</td><td>${r.empresa}</td><td>${r.cargo}</td><td>${r.condicion}</td></tr>`).join('');drawCharts(reps);}
function drawCharts(reps){const byEmp={};reps.forEach(r=>byEmp[r.empresa]=(byEmp[r.empresa]||0)+1);const cond={'Sin síntomas':0,'Con síntomas':0};reps.forEach(r=>cond[r.condicion]++);if(chartEmpresas)chartEmpresas.destroy();if(chartCondicion)chartCondicion.destroy();chartEmpresas=new Chart(document.getElementById('chartEmpresas'),{type:'pie',data:{labels:Object.keys(byEmp),datasets:[{data:Object.values(byEmp)}]}});chartCondicion=new Chart(document.getElementById('chartCondicion'),{type:'pie',data:{labels:Object.keys(cond),datasets:[{data:Object.values(cond)}]}});}
function exportarCSV(){const rows=get('reportes').map(r=>[r.fecha,r.hora,r.dni,r.trabajador,r.empresa,r.cargo,r.sede,r.condicion]);const csv='fecha,hora,dni,trabajador,empresa,cargo,sede,condicion\n'+rows.map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='reportes_salud.csv';a.click();}
function renderAll(){renderTrabajadores();renderDashboard();}
seed();buildQuestions();renderAll();
