const ACTIVIDADES=['Trabajos en Altura','Trabajos en Caliente','Trabajos en Espacio Confinado','Trabajos en Izaje mecánico de cargas','Trabajos de Excavación o Demolición','Trabajos con Aislamiento de Energía'];
const SINTOMAS=['Dolor de cabeza','Mareos o sensación de inestabilidad','Visión borrosa o doble','Náuseas o vómitos','Falta de aire / dificultad para respirar','Dolor en alguna parte del cuerpo','Dolor o presión en el pecho','Palpitaciones o taquicardia','Fiebre o escalofríos','Fatiga o somnolencia','Pérdida de equilibrio','Zumbido/dolor de oídos','Sensación de desmayo'];
const MODO=new URL(location.href).searchParams.get('view');let trabajadorActual=null,empresasCache=[],chart1=null,chart2=null;
function today(){return new Date().toISOString().slice(0,10)}
function showView(id){if(MODO==='trabajador'&&id!=='trabajador')id='trabajador';document.querySelectorAll('main section').forEach(s=>s.classList.add('hidden'));const el=document.getElementById(id);if(el)el.classList.remove('hidden');if(MODO==='trabajador'){document.getElementById('home')?.remove();document.getElementById('admin')?.remove();document.querySelectorAll('#trabajador .back').forEach(a=>a.textContent='← Salir')}}
function salirTrabajador(){dniBuscar.value='';trabajadorActual=null;datosTrab.classList.add('hidden');formReporte.classList.add('hidden');formReporte.reset();bloqueEncuesta.classList.add('hidden');bloqueNoRiesgo.classList.add('hidden');toast('Sesión finalizada')}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3500)}
async function api(action,data={}){if(!API_URL||API_URL.includes('PEGA_AQUI'))throw new Error('Falta configurar API_URL');const r=await fetch(API_URL,{method:'POST',body:JSON.stringify({action,...data})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Operación no válida');return j}
function dniOk(v){return /^\d{8}$/.test(String(v||'').trim())}
async function loadEmpresas(){const r=await api('listarEmpresas');empresasCache=r.empresas||[];return empresasCache}
function fillSelect(id,all=false){const s=document.getElementById(id);if(!s)return;s.innerHTML=all?'<option value="">Todas las empresas</option>':'<option value="">Empresa *</option>';empresasCache.forEach(e=>s.innerHTML+=`<option>${e.Empresa}</option>`)}
function initChecks(){acts.innerHTML=ACTIVIDADES.map(a=>`<label class="check"><input type="checkbox" data-act="${a}" value="SI"><span>${a}</span></label>`).join('');sints.innerHTML=SINTOMAS.map(a=>`<label class="check"><input type="checkbox" data-sint="${a}" value="SI"><span>${a}</span></label>`).join('')}
async function buscarTrabajador(){try{const d=dniBuscar.value.trim();if(!dniOk(d))return toast('DNI debe tener 8 dígitos, incluyendo 0 inicial si corresponde');const r=await api('buscarTrabajador',{dni:d});if(!r.trabajador){datosTrab.classList.remove('hidden');datosTrab.innerHTML='<b>DNI no se encuentra activo en la master.</b>';formReporte.classList.add('hidden');return}trabajadorActual=r.trabajador;datosTrab.classList.remove('hidden');datosTrab.innerHTML=`<b>${r.trabajador.Nombres}</b><br>${r.trabajador.Cargo} · ${r.trabajador.Empresa} · ${r.trabajador.Sede}<br>Celular: ${r.trabajador.Celular||''}`;formReporte.classList.remove('hidden')}catch(e){toast(e.message)}}
function toggleAltoRiesgo(){bloqueNoRiesgo.classList.toggle('hidden',altoRiesgo.value!=='NO');bloqueEncuesta.classList.toggle('hidden',altoRiesgo.value!=='SI')}
function toggleSintomas(){const v=document.querySelector('input[name="repSint"]:checked')?.value;bloqueSintomas.classList.toggle('hidden',v!=='SI')}
async function finalizarSinRiesgo(){await guardarReporteFinal('NO',{}, {}, 'SIN SÍNTOMAS', 'No ejecuta actividad de alto riesgo')}
formReporte.onsubmit=async ev=>{ev.preventDefault();try{if(!trabajadorActual)return toast('Busque primero al trabajador');if(altoRiesgo.value==='NO')return finalizarSinRiesgo();if(altoRiesgo.value!=='SI')return toast('Seleccione si ejecutará actividad de alto riesgo');let Actividades={};document.querySelectorAll('[data-act]').forEach(x=>{if(x.checked)Actividades[x.dataset.act]='SI'});if(!Object.keys(Actividades).length)return toast('Seleccione al menos una actividad de alto riesgo');const rep=document.querySelector('input[name="repSint"]:checked')?.value;if(!rep)return toast('Seleccione si presenta síntomas');let Sintomas={};if(rep==='SI'){document.querySelectorAll('[data-sint]').forEach(x=>{if(x.checked)Sintomas[x.dataset.sint]='SI'});if(!Object.keys(Sintomas).length)return toast('Seleccione al menos un síntoma')}const condicion=rep==='SI'?'CON SÍNTOMAS':'SIN SÍNTOMAS';await guardarReporteFinal('SI',Actividades,Sintomas,condicion,'') }catch(e){toast(e.message)}}
async function guardarReporteFinal(ejecuta,Actividades,Sintomas,Condicion,obs){const reporte={...trabajadorActual,DNI:String(trabajadorActual.DNI),EjecutaAltoRiesgo:ejecuta,Actividades,Sintomas,Observacion:obs,Condicion,DeclaracionVeraz:'SI'};await api('guardarReporte',{reporte});alert('Registro finalizado. Se le recuerda que si durante su jornada de trabajo presenta algún síntoma descrito anteriormente deberá comunicar a su jefe inmediato antes de ejecutar cualquier trabajo de alto riesgo.');salirTrabajador()}
async function initEmpresa(){await loadEmpresas();fillSelect('temp');fillSelect('fempGestion',true);listarTrabajadores()}
async function guardarTrabajador(){try{const t={DNI:tdni.value.trim(),Nombres:tnom.value.trim(),Cargo:tcargo.value.trim(),Empresa:temp.value,Sede:tsede.value,Rubro:'',Correo:tcorreo.value.trim(),Celular:tcelular.value.trim(),Estado:test.value};if(!dniOk(t.DNI))return toast('DNI debe tener 8 dígitos');if(['Nombres','Cargo','Empresa','Sede','Correo','Celular','Estado'].some(k=>!t[k]))return toast('Todos los campos son obligatorios');await api('guardarTrabajador',{trabajador:t});toast('Trabajador guardado');listarTrabajadores()}catch(e){toast(e.message)}}
async function listarTrabajadores(){try{const r=await api('listarTrabajadores',{empresa:fempGestion.value});const arr=r.trabajadores||[];tablaTrab.innerHTML='<table class="table"><tr><th>DNI</th><th>Nombres</th><th>Cargo</th><th>Empresa</th><th>Celular</th><th>Estado</th><th>Acción</th></tr>'+arr.map(x=>`<tr><td>${x.DNI}</td><td>${x.Nombres}</td><td>${x.Cargo}</td><td>${x.Empresa}</td><td>${x.Celular||''}</td><td>${x.Estado}</td><td><button class="secondary" onclick='editTrab(${JSON.stringify(x)})'>Editar</button></td></tr>`).join('')+'</table>'}catch(e){toast(e.message)}}
function editTrab(x){if(!confirm(`Está editando los datos de:\n\nTrabajador: ${x.Nombres}\nDNI: ${x.DNI}\nEmpresa: ${x.Empresa}\n\n¿Desea continuar?`))return;tdni.value=x.DNI;tnom.value=x.Nombres;tcargo.value=x.Cargo;temp.value=x.Empresa;tsede.value=x.Sede;tcorreo.value=x.Correo;tcelular.value=x.Celular||'';test.value=x.Estado;scrollTo(0,0)}
async function initEmpresas(){await loadEmpresas();tablaEmp.innerHTML='<table class="table"><tr><th>Empresa</th><th>Correo doctor o personal de Salud</th></tr>'+empresasCache.map(e=>`<tr><td>${e.Empresa}</td><td>${e.CorreoDoctor}</td></tr>`).join('')+'</table>'}
async function guardarEmpresa(){try{if(!enombre.value.trim()||!edoctor.value.trim())return toast('Complete empresa y correo médico');await api('guardarEmpresa',{empresa:{Empresa:enombre.value.trim(),CorreoDoctor:edoctor.value.trim()}});toast('Empresa guardada');enombre.value=edoctor.value='';initEmpresas()}catch(e){toast(e.message)}}
async function initDashboard(){await loadEmpresas();fillSelect('dashEmp',true);dashFecha.value=today();dashMes.value=today().slice(0,7);loadDashboard()}
async function loadDashboard(){try{const modo=dashFechaModo.value;const fecha=modo==='dia'?dashFecha.value:'';const mes=modo==='mes'?dashMes.value:'';const r=await api('dashboard',{fecha,mes,empresa:dashEmp.value,condicion:dashCond.value});kpis.innerHTML=`<div class="kpi"><b>${r.totalTrabajadores}</b><br>Master activa</div><div class="kpi"><b>${r.totalReportes}</b><br>Reportes</div><div class="kpi"><b>${r.conSintomas}</b><br>Con síntomas</div><div class="kpi"><b>${r.cumplimiento}%</b><br>Cumplimiento</div>`;tablaDash.innerHTML='<table class="table"><tr><th>Fecha</th><th>DNI</th><th>Trabajador</th><th>Empresa</th><th>Celular</th><th>Condición</th></tr>'+(r.reportes||[]).map(x=>`<tr><td>${x.Fecha}</td><td>${x.DNI}</td><td>${x.Nombres}</td><td>${x.Empresa}</td><td>${x.Celular||''}</td><td>${x.Condicion}</td></tr>`).join('')+'</table>';renderCharts(r)}catch(e){toast(e.message)}}
function renderCharts(r){if(chart1)chart1.destroy();if(chart2)chart2.destroy();chart1=new Chart(document.getElementById('chartCumplimiento'),{type:'bar',data:{labels:(r.cumplimientoPorEmpresa||[]).map(x=>x.Empresa),datasets:[{label:'Cumplimiento %',data:(r.cumplimientoPorEmpresa||[]).map(x=>x.Cumplimiento)}]},options:{scales:{y:{beginAtZero:true,max:100}}}});chart2=new Chart(document.getElementById('chartSintomas'),{type:'bar',data:{labels:(r.sintomasResumen||[]).map(x=>x.Sintoma),datasets:[{label:'Cantidad',data:(r.sintomasResumen||[]).map(x=>x.Cantidad)}]},options:{indexAxis:'y',scales:{x:{beginAtZero:true}}}})}
async function initValidar(){await loadEmpresas();fillSelect('valEmp',true);valFecha.value=today()}
async function validarPermiso(){try{const dnis=(valDnis.value.match(/\d{8}/g)||[]);if(!dnis.length)return toast('Ingrese al menos un DNI válido de 8 dígitos');const r=await api('validarPermiso',{dnis,fecha:valFecha.value,empresa:valEmp.value});resValidacion.innerHTML=(r.resultado||[]).map(x=>{if(x.estado==='NO_MASTER')return `<div class="bad">❌ DNI ${x.DNI} no se encuentra en la Master</div>`;if(x.estado==='NO_REPORTO')return `<div class="warn">⚠️ Trabajador no generó reporte de síntomas: <b>${x.Nombres}</b> / DNI ${x.DNI}</div>`;if(String(x.condicion).includes('CON SÍNTOMAS'))return `<div class="bad">🚨 Trabajador <b>${x.Nombres}</b> / DNI ${x.DNI} presenta síntomas</div>`;return `<div class="ok">✅ ${x.Nombres} / DNI ${x.DNI}: trabajador no reporta síntomas para hoy</div>`}).join('')}catch(e){toast(e.message)}}
window.onload=()=>{initChecks();if(MODO==='trabajador')showView('trabajador');else if(MODO==='admin')showView('admin');else showView('home');if(document.getElementById('dashFecha'))dashFecha.value=today();if(document.getElementById('valFecha'))valFecha.value=today()}
